name: Build Docker Images

# When first developing this we experienced issues with GHA runners where they ran out of disk space.
# It doesn't seem to be a problem, but if it happens again, one measure we can take is to add
# the jlumbroso/free-disk-space@main action, which removes some preinstalled tools from runners.

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  # Build the "builder" image.
  builder:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: builder
          file: builder/Dockerfile
          # Build the image then push it to the registry.
          push: true
          tags: ghcr.io/${{ github.repository }}/builder:latest
          # Cache layers in the GHA Cache.
          # This results in huge improvements in build times.
          cache-from: type=gha
          cache-to: type=gha,mode=max
