name: Build Docker Images

# When first developing this we experienced issues with GHA runners where they ran out of disk space.
# It doesn't seem to be a problem, but if it happens again, one measure we can take is to add
# the jlumbroso/free-disk-space@main action, which removes some preinstalled tools from runners.

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request: # DELETEME

jobs:
  # This job builds the private infrastructure images that are used as the basis for creating the public images.
  infra:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/bake-action@v5
        with:
          targets: infra
          push: true
          # Use the GHA cache to speed things up
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
        env:
          BUILD_ENV: prod

  # This job builds the public images that users pull and use.
  # It depends on infra because public Dockerfiles use FROM ghcr.io/.../builder and FROM ghcr.io/.../base
  public:
    needs: infra
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/bake-action@v5
        with:
          targets: public
          push: true
          # Use the GHA cache to speed things up
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
        env:
          BUILD_ENV: prod
